services:
  nav2:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        IMAGE_NAME: ${IMAGE_NAME}
        ROS_DISTRO_NAME: ${ROS_DISTRO_NAME}
      target: nav2
    image: nav2-${ROS_DISTRO_NAME}-docker
    container_name: ${CONTAINER_NAME:-nav2-${ROS_DISTRO_NAME}-docker}
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      DISPLAY: ${DISPLAY}
    working_dir: /root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ./example_ws:/root/example_ws
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    tty: true
