services:
  ros:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      #network: host
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        IMAGE_NAME: ${IMAGE_NAME}
        ROS_DISTRO_NAME: ${ROS_DISTRO_NAME}
      target: ros2
    image: ros-${ROS_DISTRO_NAME}-docker
    # If CONTAINER_NAME is not provided, fall back to a deterministic name.
    container_name: ${CONTAINER_NAME:-ros-${ROS_DISTRO_NAME}-docker}
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      #no_proxy: ${no_proxy}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      #NO_PROXY: ${no_proxy}
      DISPLAY: ${DISPLAY}
    working_dir: /root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - ./example_ws:/root/example_ws
    devices:
      - /dev/bus/usb:/dev/bus/usb
    privileged: true
    tty: true
